//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teraque.ExplorerChromeExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teraque.ExplorerChromeExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Teraque, Inc.  All rights reserved..
        /// </summary>
        public static string AboutCopyrightNotice {
            get {
                return ResourceManager.GetString("AboutCopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} days left in your evaluation period..
        /// </summary>
        public static string AboutEvaluationDaysLeftFormat {
            get {
                return ResourceManager.GetString("AboutEvaluationDaysLeftFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation License.
        /// </summary>
        public static string AboutEvaluationLicense {
            get {
                return ResourceManager.GetString("AboutEvaluationLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:sales@teraque.com.
        /// </summary>
        public static string AboutMailUrl {
            get {
                return ResourceManager.GetString("AboutMailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is not licensed..
        /// </summary>
        public static string AboutNotLicensed {
            get {
                return ResourceManager.GetString("AboutNotLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Chrome Suite.
        /// </summary>
        public static string AboutProductName {
            get {
                return ResourceManager.GetString("AboutProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.teraque.com/products/explorer-chrome-suite/.
        /// </summary>
        public static string AboutPurchaseLicenseUrl {
            get {
                return ResourceManager.GetString("AboutPurchaseLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support at Teraque.
        /// </summary>
        public static string AboutSupportHome {
            get {
                return ResourceManager.GetString("AboutSupportHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@teraque.com.
        /// </summary>
        public static string AboutSupportMail {
            get {
                return ResourceManager.GetString("AboutSupportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get help at.
        /// </summary>
        public static string AboutSupportMessageRun0 {
            get {
                return ResourceManager.GetString("AboutSupportMessageRun0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or email us at .
        /// </summary>
        public static string AboutSupportMessageRun1 {
            get {
                return ResourceManager.GetString("AboutSupportMessageRun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  We&apos;re happy to answer your questions even if you&apos;re just evaluating the product..
        /// </summary>
        public static string AboutSupportMessageRun2 {
            get {
                return ResourceManager.GetString("AboutSupportMessageRun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.teraque.com/support.
        /// </summary>
        public static string AboutSupportUrl {
            get {
                return ResourceManager.GetString("AboutSupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Explorer Chrome Suite.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} days left on your license..
        /// </summary>
        public static string AboutValidDaysLeftFormat {
            get {
                return ResourceManager.GetString("AboutValidDaysLeftFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is licensed..
        /// </summary>
        public static string AboutValidLicense {
            get {
                return ResourceManager.GetString("AboutValidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conten_t.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The evaluation period for &apos;{0}&apos; has expired.  Please contact Teraque support for a solution at 1.617.963.8999 or support@teraque.com..
        /// </summary>
        public static string EvaluationLicense {
            get {
                return ResourceManager.GetString("EvaluationLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license for &apos;{0}&apos; has expired.  Please contact the Teraque support for a solution at 1.617.963.8999 or support@teraque.com..
        /// </summary>
        public static string ExpiredLicense {
            get {
                return ResourceManager.GetString("ExpiredLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xtra large icons.
        /// </summary>
        public static string ExtraLargeIcons {
            get {
                return ResourceManager.GetString("ExtraLargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid license could not be found for &apos;{0}&apos;.  Please contact the Teraque support for a solution at 1.617.963.8999 or support@teraque.com..
        /// </summary>
        public static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La_rge icons.
        /// </summary>
        public static string LargeIcons {
            get {
                return ResourceManager.GetString("LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Medium icons.
        /// </summary>
        public static string MediumIcons {
            get {
                return ResourceManager.GetString("MediumIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _List.
        /// </summary>
        public static string SimpleList {
            get {
                return ResourceManager.GetString("SimpleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small ico_ns.
        /// </summary>
        public static string SmallIcons {
            get {
                return ResourceManager.GetString("SmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status _bar.
        /// </summary>
        public static string StatusBar {
            get {
                return ResourceManager.GetString("StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile_s.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Chrome Suite Example.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
