namespace Teraque
{

    using System.Collections.Generic;
	using System.Windows;

	/// <summary>
	/// Describes the data generated by a column deletion event.
	/// </summary>
	public class ColumnDefinitionsEventArgs : RoutedEventArgs
	{

		/// <summary>
		/// The column that was deleted.
		/// </summary>
		public readonly System.Collections.Generic.List<ReportColumn> Columns;

		public ColumnDefinitionsEventArgs(RoutedEvent routedEvent, ReportColumn reportColumn) : base(routedEvent)
		{

			// Initialize the object.
			this.Columns = new List<ReportColumn>();
			this.Columns.Add(reportColumn);

		}

		/// <summary>
		/// Creates an object used to describe a column deletion event.
		/// </summary>
		/// <param name="column">The column that was deleted.</param>
		public ColumnDefinitionsEventArgs(RoutedEvent routedEvent, List<ReportColumn> columns) : base(routedEvent)
		{

			// Initialize the object.
			this.Columns = columns;

		}

	}

}
