namespace Teraque
{

    using System.Windows;
	using System.Windows.Controls;

	public delegate void ColumnChangedEventHandler(object sender, ColumnChangedEventArgs columnChangedEventArgs);

	/// <summary>
	/// Describes the data generated by a column deletion event.
	/// </summary>
	public class ColumnChangedEventArgs : RoutedEventArgs
	{

		// Public Instance Fields
		public readonly ReportColumn ColumnDefinition;
		public readonly System.Object OldValue;
		public readonly System.Object NewValue;
		public readonly System.Windows.DependencyProperty DependencyProperty;
		public readonly System.Windows.Controls.UndoAction UndoAction;

		public ColumnChangedEventArgs(RoutedEvent routedEvent, UndoAction undoAction,
			ReportColumn reportColumn, DependencyProperty dependencyProperty,
			object oldValue, object newValue)
			: base(routedEvent)
		{

			// Initialize the object.
			this.UndoAction = undoAction;
			this.ColumnDefinition = reportColumn;
			this.DependencyProperty = dependencyProperty;
			this.OldValue = oldValue;
			this.NewValue = newValue;

		}

	}

}
