namespace Teraque
{

	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Describes the data generated by a row deletion event.
	/// </summary>
	public class RowDefinitionsEventArgs : EventArgs
	{

		/// <summary>
		/// The row that was deleted.
		/// </summary>
		public readonly System.Collections.Generic.List<ReportRow> Rows;

		public RowDefinitionsEventArgs(ReportRow reportRow)
		{

			// Initialize the object.
			this.Rows = new List<ReportRow>();
			this.Rows.Add(reportRow);

		}

		/// <summary>
		/// Creates an object used to describe a row deletion event.
		/// </summary>
		/// <param name="row">The row that was deleted.</param>
		public RowDefinitionsEventArgs(List<ReportRow> rows)
		{

			// Initialize the object.
			this.Rows = rows;

		}

	}

}
