//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teraque.AssetNetwork.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DestinationOrderInfo", Namespace="http://schemas.datacontract.org/2004/07/Teraque.AssetNetwork")]
    [System.SerializableAttribute()]
    public partial class DestinationOrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BlotterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DestinationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teraque.OrderTypeCode OrderTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SecurityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SettlementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teraque.SideCode SideCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teraque.TimeInForceCode TimeInForceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WorkingOrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BlotterId {
            get {
                return this.BlotterIdField;
            }
            set {
                if ((this.BlotterIdField.Equals(value) != true)) {
                    this.BlotterIdField = value;
                    this.RaisePropertyChanged("BlotterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teraque.OrderTypeCode OrderTypeCode {
            get {
                return this.OrderTypeCodeField;
            }
            set {
                if ((this.OrderTypeCodeField.Equals(value) != true)) {
                    this.OrderTypeCodeField = value;
                    this.RaisePropertyChanged("OrderTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderedQuantity {
            get {
                return this.OrderedQuantityField;
            }
            set {
                if ((this.OrderedQuantityField.Equals(value) != true)) {
                    this.OrderedQuantityField = value;
                    this.RaisePropertyChanged("OrderedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SecurityId {
            get {
                return this.SecurityIdField;
            }
            set {
                if ((this.SecurityIdField.Equals(value) != true)) {
                    this.SecurityIdField = value;
                    this.RaisePropertyChanged("SecurityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SettlementId {
            get {
                return this.SettlementIdField;
            }
            set {
                if ((this.SettlementIdField.Equals(value) != true)) {
                    this.SettlementIdField = value;
                    this.RaisePropertyChanged("SettlementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teraque.SideCode SideCode {
            get {
                return this.SideCodeField;
            }
            set {
                if ((this.SideCodeField.Equals(value) != true)) {
                    this.SideCodeField = value;
                    this.RaisePropertyChanged("SideCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teraque.TimeInForceCode TimeInForceCode {
            get {
                return this.TimeInForceCodeField;
            }
            set {
                if ((this.TimeInForceCodeField.Equals(value) != true)) {
                    this.TimeInForceCodeField = value;
                    this.RaisePropertyChanged("TimeInForceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorkingOrderId {
            get {
                return this.WorkingOrderIdField;
            }
            set {
                if ((this.WorkingOrderIdField.Equals(value) != true)) {
                    this.WorkingOrderIdField = value;
                    this.RaisePropertyChanged("WorkingOrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DestinationOrderReference", Namespace="http://schemas.datacontract.org/2004/07/Teraque.AssetNetwork")]
    [System.SerializableAttribute()]
    public partial class DestinationOrderReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DestinationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RowVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((this.RowVersionField.Equals(value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quote", Namespace="http://schemas.datacontract.org/2004/07/Teraque.AssetNetwork")]
    [System.SerializableAttribute()]
    public partial class Quote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AskPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AskSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BidPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BidSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LastPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LastSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AskPrice {
            get {
                return this.AskPriceField;
            }
            set {
                if ((this.AskPriceField.Equals(value) != true)) {
                    this.AskPriceField = value;
                    this.RaisePropertyChanged("AskPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AskSize {
            get {
                return this.AskSizeField;
            }
            set {
                if ((this.AskSizeField.Equals(value) != true)) {
                    this.AskSizeField = value;
                    this.RaisePropertyChanged("AskSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BidPrice {
            get {
                return this.BidPriceField;
            }
            set {
                if ((this.BidPriceField.Equals(value) != true)) {
                    this.BidPriceField = value;
                    this.RaisePropertyChanged("BidPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BidSize {
            get {
                return this.BidSizeField;
            }
            set {
                if ((this.BidSizeField.Equals(value) != true)) {
                    this.BidSizeField = value;
                    this.RaisePropertyChanged("BidSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LastPrice {
            get {
                return this.LastPriceField;
            }
            set {
                if ((this.LastPriceField.Equals(value) != true)) {
                    this.LastPriceField = value;
                    this.RaisePropertyChanged("LastPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LastSize {
            get {
                return this.LastSizeField;
            }
            set {
                if ((this.LastSizeField.Equals(value) != true)) {
                    this.LastSizeField = value;
                    this.RaisePropertyChanged("LastSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IWebService")]
    public interface IWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ClearOrders", ReplyAction="http://tempuri.org/IWebService/ClearOrdersResponse")]
        void ClearOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ClearOrders", ReplyAction="http://tempuri.org/IWebService/ClearOrdersResponse")]
        System.Threading.Tasks.Task ClearOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CreateDestinationOrders", ReplyAction="http://tempuri.org/IWebService/CreateDestinationOrdersResponse")]
        void CreateDestinationOrders(Teraque.AssetNetwork.WebService.DestinationOrderInfo[] destinationOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/CreateDestinationOrders", ReplyAction="http://tempuri.org/IWebService/CreateDestinationOrdersResponse")]
        System.Threading.Tasks.Task CreateDestinationOrdersAsync(Teraque.AssetNetwork.WebService.DestinationOrderInfo[] destinationOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DestroyDestinationOrders", ReplyAction="http://tempuri.org/IWebService/DestroyDestinationOrdersResponse")]
        void DestroyDestinationOrders(Teraque.AssetNetwork.WebService.DestinationOrderReference[] destinationOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DestroyDestinationOrders", ReplyAction="http://tempuri.org/IWebService/DestroyDestinationOrdersResponse")]
        System.Threading.Tasks.Task DestroyDestinationOrdersAsync(Teraque.AssetNetwork.WebService.DestinationOrderReference[] destinationOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTenants", ReplyAction="http://tempuri.org/IWebService/GetTenantsResponse")]
        string[] GetTenants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTenants", ReplyAction="http://tempuri.org/IWebService/GetTenantsResponse")]
        System.Threading.Tasks.Task<string[]> GetTenantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserId", ReplyAction="http://tempuri.org/IWebService/GetUserIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Teraque.RecordNotFoundFault), Action="http://tempuri.org/IWebService/GetUserIdRecordNotFoundFaultFault", Name="RecordNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/Teraque")]
        System.Guid GetUserId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserId", ReplyAction="http://tempuri.org/IWebService/GetUserIdResponse")]
        System.Threading.Tasks.Task<System.Guid> GetUserIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/LoadTenant", ReplyAction="http://tempuri.org/IWebService/LoadTenantResponse")]
        void LoadTenant(string tenantName, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/LoadTenant", ReplyAction="http://tempuri.org/IWebService/LoadTenantResponse")]
        System.Threading.Tasks.Task LoadTenantAsync(string tenantName, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ReportExecution", ReplyAction="http://tempuri.org/IWebService/ReportExecutionResponse")]
        void ReportExecution(Teraque.Message[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ReportExecution", ReplyAction="http://tempuri.org/IWebService/ReportExecutionResponse")]
        System.Threading.Tasks.Task ReportExecutionAsync(Teraque.Message[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Start", ReplyAction="http://tempuri.org/IWebService/StartResponse")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Start", ReplyAction="http://tempuri.org/IWebService/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Stop", ReplyAction="http://tempuri.org/IWebService/StopResponse")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Stop", ReplyAction="http://tempuri.org/IWebService/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UnloadTenant", ReplyAction="http://tempuri.org/IWebService/UnloadTenantResponse")]
        void UnloadTenant(string tenantName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UnloadTenant", ReplyAction="http://tempuri.org/IWebService/UnloadTenantResponse")]
        System.Threading.Tasks.Task UnloadTenantAsync(string tenantName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCanadaTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCanadaTickerPriceResponse")]
        void UpdateCanadaTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCanadaTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCanadaTickerPriceResponse")]
        System.Threading.Tasks.Task UpdateCanadaTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCusipPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCusipPriceResponse")]
        void UpdateCusipPrice(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCusipPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCusipPriceResponse")]
        System.Threading.Tasks.Task UpdateCusipPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCurrencyPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCurrencyPriceResponse")]
        void UpdateCurrencyPrice(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateCurrencyPrice", ReplyAction="http://tempuri.org/IWebService/UpdateCurrencyPriceResponse")]
        System.Threading.Tasks.Task UpdateCurrencyPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdatePrice", ReplyAction="http://tempuri.org/IWebService/UpdatePriceResponse")]
        void UpdatePrice(System.Collections.Generic.Dictionary<string, Teraque.AssetNetwork.WebService.Quote[]> quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdatePrice", ReplyAction="http://tempuri.org/IWebService/UpdatePriceResponse")]
        System.Threading.Tasks.Task UpdatePriceAsync(System.Collections.Generic.Dictionary<string, Teraque.AssetNetwork.WebService.Quote[]> quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUnitedKingdomTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateUnitedKingdomTickerPriceResponse")]
        void UpdateUnitedKingdomTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUnitedKingdomTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateUnitedKingdomTickerPriceResponse")]
        System.Threading.Tasks.Task UpdateUnitedKingdomTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUnitedStatesTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateUnitedStatesTickerPriceResponse")]
        void UpdateUnitedStatesTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UpdateUnitedStatesTickerPrice", ReplyAction="http://tempuri.org/IWebService/UpdateUnitedStatesTickerPriceResponse")]
        System.Threading.Tasks.Task UpdateUnitedStatesTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceChannel : Teraque.AssetNetwork.WebService.IWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<Teraque.AssetNetwork.WebService.IWebService>, Teraque.AssetNetwork.WebService.IWebService {
        
        public WebServiceClient() {
        }
        
        public WebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearOrders() {
            base.Channel.ClearOrders();
        }
        
        public System.Threading.Tasks.Task ClearOrdersAsync() {
            return base.Channel.ClearOrdersAsync();
        }
        
        public void CreateDestinationOrders(Teraque.AssetNetwork.WebService.DestinationOrderInfo[] destinationOrders) {
            base.Channel.CreateDestinationOrders(destinationOrders);
        }
        
        public System.Threading.Tasks.Task CreateDestinationOrdersAsync(Teraque.AssetNetwork.WebService.DestinationOrderInfo[] destinationOrders) {
            return base.Channel.CreateDestinationOrdersAsync(destinationOrders);
        }
        
        public void DestroyDestinationOrders(Teraque.AssetNetwork.WebService.DestinationOrderReference[] destinationOrders) {
            base.Channel.DestroyDestinationOrders(destinationOrders);
        }
        
        public System.Threading.Tasks.Task DestroyDestinationOrdersAsync(Teraque.AssetNetwork.WebService.DestinationOrderReference[] destinationOrders) {
            return base.Channel.DestroyDestinationOrdersAsync(destinationOrders);
        }
        
        public string[] GetTenants() {
            return base.Channel.GetTenants();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTenantsAsync() {
            return base.Channel.GetTenantsAsync();
        }
        
        public System.Guid GetUserId() {
            return base.Channel.GetUserId();
        }
        
        public System.Threading.Tasks.Task<System.Guid> GetUserIdAsync() {
            return base.Channel.GetUserIdAsync();
        }
        
        public void LoadTenant(string tenantName, string connectionString) {
            base.Channel.LoadTenant(tenantName, connectionString);
        }
        
        public System.Threading.Tasks.Task LoadTenantAsync(string tenantName, string connectionString) {
            return base.Channel.LoadTenantAsync(tenantName, connectionString);
        }
        
        public void ReportExecution(Teraque.Message[] messages) {
            base.Channel.ReportExecution(messages);
        }
        
        public System.Threading.Tasks.Task ReportExecutionAsync(Teraque.Message[] messages) {
            return base.Channel.ReportExecutionAsync(messages);
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public System.Threading.Tasks.Task StopAsync() {
            return base.Channel.StopAsync();
        }
        
        public void UnloadTenant(string tenantName) {
            base.Channel.UnloadTenant(tenantName);
        }
        
        public System.Threading.Tasks.Task UnloadTenantAsync(string tenantName) {
            return base.Channel.UnloadTenantAsync(tenantName);
        }
        
        public void UpdateCanadaTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            base.Channel.UpdateCanadaTickerPrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdateCanadaTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            return base.Channel.UpdateCanadaTickerPriceAsync(quotes);
        }
        
        public void UpdateCusipPrice(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            base.Channel.UpdateCusipPrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdateCusipPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            return base.Channel.UpdateCusipPriceAsync(quotes);
        }
        
        public void UpdateCurrencyPrice(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            base.Channel.UpdateCurrencyPrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdateCurrencyPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            return base.Channel.UpdateCurrencyPriceAsync(quotes);
        }
        
        public void UpdatePrice(System.Collections.Generic.Dictionary<string, Teraque.AssetNetwork.WebService.Quote[]> quotes) {
            base.Channel.UpdatePrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdatePriceAsync(System.Collections.Generic.Dictionary<string, Teraque.AssetNetwork.WebService.Quote[]> quotes) {
            return base.Channel.UpdatePriceAsync(quotes);
        }
        
        public void UpdateUnitedKingdomTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            base.Channel.UpdateUnitedKingdomTickerPrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdateUnitedKingdomTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            return base.Channel.UpdateUnitedKingdomTickerPriceAsync(quotes);
        }
        
        public void UpdateUnitedStatesTickerPrice(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            base.Channel.UpdateUnitedStatesTickerPrice(quotes);
        }
        
        public System.Threading.Tasks.Task UpdateUnitedStatesTickerPriceAsync(Teraque.AssetNetwork.WebService.Quote[] quotes) {
            return base.Channel.UpdateUnitedStatesTickerPriceAsync(quotes);
        }
    }
}
