# Scrape the Visual Studio 2008 Solution files and put them in the setup directories so they can be deployed.
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Explorer Chrome Suite.sln" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
$(Get-Item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Explorer Chrome Suite.suo").Attributes = ‘Normal’
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Explorer Chrome Suite.suo" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Category Page\Category Page.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Category Page\Category Page.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Data Model\Data Model.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Data Model\Data Model.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Explorer Chrome Example\Explorer Chrome Example.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2008\Explorer Chrome Example\Explorer Chrome Example.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2008"
# Scrape the Visual Studio 2010 Solution files and put them in the setup directories so they can be deployed.
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Explorer Chrome Suite.sln" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
$(Get-Item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Explorer Chrome Suite.suo").Attributes = ‘Normal’
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Explorer Chrome Suite.suo" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Category Page\Category Page.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Category Page\Category Page.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Data Model\Data Model.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Data Model\Data Model.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Explorer Chrome Example\Explorer Chrome Example.csproj" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"
copy-item -force "C:\Program Files (x86)\Teraque\Explorer Chrome Suite\Examples\Visual Studio 2010\Explorer Chrome Example\Explorer Chrome Example.csproj.user" "${Home}\Documents\Visual Studio 2010\Projects\Teraque\Main\Explorer Chrome Suite\Setup x86\Visual Studio 2010"

